### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by nazo6** [nazo6/lspinstall.nvim#13]
- [ ] Rewrite the installation process and screen display. (code is super ugly)
   - https://github.com/williamboman/nvim-lsp-installer looks very good.
- [ ] Remove plenary dependency
   - [ ] Async
   - [ ] Job 
- [ ] Add more debug adapters
   - https://github.com/Pocco81/DAPInstall.nvim
- [ ] Command chain functions

**Comment by nazo6** [comment]
I will do it when I get motivated.
